version: '3.8'

services:
  manga-api:
    build: .
    container_name: manga-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - manga-network

networks:
  manga-network:
    driver: bridge 